# Generated by Django 4.2.4 on 2023-08-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.AddField(
            model_name='chapter',
            name='year',
            field=models.CharField(choices=[('1', 'MP2I'), ('2', 'MPI')], default='1', max_length=1),
        ),
    ]
